### ISSUE TITLE
Can you share a printable layout?

### ISSUE THREAD

**Issue by Krumpet** [Dwctor/Kaly#4]
I want to compare the layout to the kyria and cantor, to see if the thumb cluster would be more comfortable for me. Thanks!

**Comment by Dwctor** [comment]
Hello!

Do any of these files sort out your issue?

![Kaly](https://github.com/Dwctor/Kaly/assets/45074062/ccde1c80-d169-4e62-b1c8-de92f6785424)
![Kaly_both_A4](https://github.com/Dwctor/Kaly/assets/45074062/9a1985fd-174a-4c6b-ad41-617edd64db4b)
![Kaly_left](https://github.com/Dwctor/Kaly/assets/45074062/fddc3223-e72b-4fd2-90f4-966d305bb1d3)

I think that the "both_A4", the second file, should have an A4 sized layout in png format that you can print onto paper! If it isn't up to your standards, feel free to use the svg (the first one) to edit!

If you think this issue has been resolved with those files, please close it when you are satisfied! Otherwise, I'll close it within a week or so.

ps: the outlines of the images are extra hard to see with Github's dark theme, but they are there! For the first one, follow the link and "save page as" and for the second one just save the image with the right click prompt!

**Comment by Krumpet** [comment]
The first one is great. I was going to suggest adding the layout to https://jhelvy.shinyapps.io/splitkbcompare/ but apparently it's not maintained any more. I think it's a useful file to share in the readme so interested folks can compare with other options. Thanks! resolving now.
