### ISSUE TITLE
Where do you buy your components?

### ISSUE THREAD

**Issue by kovasap** [Dwctor/Kaly#6]
Thanks for creating this project and I'm excited to try building my own kaly!

I'm curious, where did you buy your components for your own build?  I've never built a board before and want to make sure I'm looking in the right places.

**Comment by DustinBracy** [comment]
I ordered my pcbs from JLCPCB, switches from lowprokb.ca, and the microcontrollers, sockets, pins and keycaps from aliexpress.  I used the weactstudio official store for the board (I got the STM32F411CEU6 v3.1 boards w/ 8M crystal, which work great, but for that specific board, you have to add the below line in your rules.mk to make the USB work right, since the default firmware expects a 25M xtal).  

BOARD = GENERIC_STM32_F411XE

**Comment by kovasap** [comment]
Thanks!  I ended up ordering from the same places, but the board was
different - I think I ended up ordering the one matching the cantor parts
list.

Excited to finish my build when it all arrives!

**Comment by kovasap** [comment]
FWIW I ended up purchasing the microcontroller at https://www.aliexpress.us/item/3256801269871873.html?spm=a2g0o.order_list.order_list_main.5.3b8c46f9NXghH7&gatewayAdapt=glo2usa, "Color:" F411 8M HSE.  It has been working great for me!

**Comment by Dwctor** [comment]
I got everything except for the PCB (JLCPCB) from aliexpress, as it was by far the cheapest option for all components.

ps: Sorry for the late reply! Forgot to read e-mails.
